# Generated by Django 4.0.1 on 2022-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread_type', models.CharField(choices=[('Baguette', 'Baguette'), ('Bagel', 'Bagel'), ('Muffin', 'Muffin'), ('Croissant', 'Croissant')], max_length=50, verbose_name='빵 종류')),
                ('bread_feature', models.CharField(max_length=50, verbose_name='특징')),
                ('bread_desc', models.TextField(verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'db_table': 'bakery_site_product',
            },
        ),
    ]
