# Generated by Django 4.0.1 on 2022-02-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('contact_number', models.CharField(max_length=50, verbose_name='연락처')),
                ('message', models.TextField(verbose_name='메세지')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '접수 관리',
                'verbose_name_plural': '접수 관리',
                'db_table': 'bakery_site_receipt',
            },
        ),
    ]
