# Generated by Django 4.0.1 on 2022-02-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=128, verbose_name='파티시엘 이름')),
                ('staff_decs', models.TextField(verbose_name='상세 정보')),
                ('staff_grade', models.CharField(choices=[('Head Shef', 'Head Shef'), ('Shef', 'Shef'), ('Assistant chef', 'Assistant chef')], default=2, max_length=50, verbose_name='직급')),
            ],
            options={
                'verbose_name': '직원',
                'verbose_name_plural': '직원',
                'db_table': 'bakery_site_staff',
            },
        ),
    ]
