# Generated by Django 4.0.1 on 2022-02-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(choices=[('Head Chef', 'Head Chef'), ('Chef', 'Chef'), ('Assistant Chef', 'Assistant Chef')], default='Chef', max_length=50, verbose_name='직급'),
        ),
    ]
