# Generated by Django 4.0.1 on 2022-02-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='사용자이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('gender', models.CharField(choices=[('M', '남자'), ('F', '여자'), ('etc', '그 이외')], max_length=10, verbose_name='성별')),
                ('contact_number', models.CharField(max_length=50, verbose_name='연락처')),
                ('address', models.CharField(max_length=256, verbose_name='주소')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'bakery_site_user',
            },
        ),
    ]
